### ISSUE TITLE
Availability of PRJEB10572 (miBC) genomes?

### ISSUE THREAD

**Issue by fplaza** [BenBeresfordJones/MGBC#15]
Hi Benjamin,

It seems that genome assemblies of the miBC are not available for download.
I see only sequencing data on the European Nucleotide Archive.
Am I missing something?

Thanks again,
Florian

**Comment by BenBeresfordJones** [comment]
Hi Florian,

The miBC assemblies have not been made available via the INDSC, so we had to reassemble them from raw reads. 
The details of the genome assembly pipeline the we used can be found in the methods section of the pre-print: https://www.biorxiv.org/content/10.1101/2021.02.11.430759v1.full

Kind regards,
Ben

**Comment by fplaza** [comment]
Hi Ben,

Do you plan to submit these sequences to the MMGC ftp repository?

**Comment by BenBeresfordJones** [comment]
Hi Florian,

Yes, I do - with the next release. 

Kind regards,
Ben

**Comment by BenBeresfordJones** [comment]
Hi Florian,

I have now updated the genome catalogue. All miBC genomes (that pass our qc) are among the 35,925 high quality genomes of the MGBC, and can be identified from the full metadata file according to their study accession (PRJEB10572). 

Best wishes,
Ben
