### ISSUE TITLE
CDS file, custom humann3 databases?

### ISSUE THREAD

**Issue by cbeekman** [BenBeresfordJones/MGBC#22]
Hi, 

The custom kraken/bracken databases worked very well for some recent datasets I generated and gave very high taxonomic classification %'s. I am currently looking into how to use your high-quality genomes to generate custom reference databases for the humann3 (https://github.com/biobakery/humann) pipeline as well.

Have you or anyone else you are aware of tried to make custom humann3 databases based on your high quality genome collection? 

In line with that wondering if you have .fna files for the predicted CDS for the high-quality genomes. I downloaded your gene predictions but these are amino acid sequences, hoping to also use nucleotide sequences for the nucleotide reference database, skipping gene prediction step might save some time.

Thanks,
Chapman

**Comment by BenBeresfordJones** [comment]
Hi Chapman,

Glad the databases are working well for you. 

Thanks for your request. We have not yet generated a custom humann3 database for the MGBC, but I will make the .ffn files (the nucleotide sequences for the predicted genes) for the hq genomes publicly available, which I hope would suffice for your work. This should be done in the next couple of days and I will ket you know when and where they can be accessed.

All the best,
Ben

**Comment by BenBeresfordJones** [comment]
This has now been finalised and the GitHub updated. The ffn files are available at: https://zenodo.org/record/6418369. 

Kind regards,
Ben
