### ISSUE TITLE
How to extract genome sequence from MGBC database?

### ISSUE THREAD

**Issue by baishengjun** [BenBeresfordJones/MGBC#25]
Hi, 
What a fantastic job! The custom kraken/bracken databases worked very well for my dataset. 
Is any solutions to extract genome sequence from MGBC database ? 

Thanks in advance
Bai

**Comment by BenBeresfordJones** [comment]
Hi Bai,

Glad to hear you are enjoying the MGBC! 

All 26,640 genomes used to build the MGBC kraken/bracken database are available from Zenodo (download link: https://zenodo.org/record/4840600/files/MGBC-hqnr_26640.tar.gz?download=1). These are the sequences used to build the database and hopefully will suit your needs. Let me know if you are having any difficulties.

Kind regards,
Benjamin
